build:
  pandoc \
    -V lang=pl \
    -H disable_float.tex \
    -H format.sty \
    -f markdown+tex_math_dollars+pipe_tables+yaml_metadata_block \
    -F mermaid-filter \
    -o ppmgr.pdf \
    ppmgr.md

watch:
  watchexec -e md just build
